-- generated by newgenasym Mon Mar 17 13:37:01 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pc049a_4lemos is
    port (    
	ANALOG_IN: OUT    std_logic_vector (3 DOWNTO 0));
end pc049a_4lemos;
