`timescale 1ns/1ns

module pc049a_lemo_daughter_board ();
// generated by  HDL Direct 16.5-S016 (v16-5-13AQ) 2/14/2012
// on Mon Mar 17 15:01:01 2014
// from uob_hep_pc049a_lib/PC049A_LEMO_DAUGHTER_BOARD/sch_1

  // global signal glbl.avdd;
  // global signal glbl.gnd_signal;

  wire  dboard_miso;
  wire  \dboard_miso* ;
  wire  dboard_mosi;
  wire  \dboard_mosi* ;
  wire  dboard_sclk;
  wire  \dboard_sclk* ;
  wire  dboard_ssn;
  wire  \dboard_ssn* ;
  wire [63:0] analog_to_maroc;
  wire [3:0] lemo_grp_a;
  wire [3:0] lemo_grp_b;
  wire [3:0] lemo_grp_c;
  wire [3:0] lemo_grp_d;
  wire [3:0] lemo_grp_e;
  wire [3:0] lemo_grp_f;
  wire [3:0] lemo_grp_g;
  wire [3:0] lemo_grp_h;
  wire [3:0] lemo_grp_i;
  wire [3:0] lemo_grp_j;
  wire [3:0] lemo_grp_k;
  wire [3:0] lemo_grp_l;
  wire [3:0] lemo_grp_m;
  wire [3:0] lemo_grp_n;
  wire [3:0] lemo_grp_o;
  wire [3:0] lemo_grp_p;

  wire [63:0] page2_analog_to_maroc;
  wire [63:0] page1_analog_to_maroc;
  wire  avdd;
  wire  page1_avdd;
  wire  gnd_signal;
  wire  page1_gnd_signal;

  assign page2_analog_to_maroc[62:62] = analog_to_maroc[62:62];
  assign page2_analog_to_maroc[58:58] = analog_to_maroc[58:58];
  assign page2_analog_to_maroc[60:60] = analog_to_maroc[60:60];
  assign page2_analog_to_maroc[56:56] = analog_to_maroc[56:56];
  assign page2_analog_to_maroc[54:54] = analog_to_maroc[54:54];
  assign page2_analog_to_maroc[50:50] = analog_to_maroc[50:50];
  assign page2_analog_to_maroc[52:52] = analog_to_maroc[52:52];
  assign page2_analog_to_maroc[48:48] = analog_to_maroc[48:48];
  assign page2_analog_to_maroc[46:46] = analog_to_maroc[46:46];
  assign page2_analog_to_maroc[42:42] = analog_to_maroc[42:42];
  assign page2_analog_to_maroc[44:44] = analog_to_maroc[44:44];
  assign page2_analog_to_maroc[40:40] = analog_to_maroc[40:40];
  assign page2_analog_to_maroc[28:28] = analog_to_maroc[28:28];
  assign page2_analog_to_maroc[34:34] = analog_to_maroc[34:34];
  assign page2_analog_to_maroc[36:36] = analog_to_maroc[36:36];
  assign page2_analog_to_maroc[32:32] = analog_to_maroc[32:32];
  assign page2_analog_to_maroc[18:18] = analog_to_maroc[18:18];
  assign page2_analog_to_maroc[20:20] = analog_to_maroc[20:20];
  assign page2_analog_to_maroc[26:26] = analog_to_maroc[26:26];
  assign page2_analog_to_maroc[24:24] = analog_to_maroc[24:24];
  assign page2_analog_to_maroc[16:16] = analog_to_maroc[16:16];
  assign page2_analog_to_maroc[14:14] = analog_to_maroc[14:14];
  assign page2_analog_to_maroc[10:10] = analog_to_maroc[10:10];
  assign page2_analog_to_maroc[12:12] = analog_to_maroc[12:12];
  assign page2_analog_to_maroc[8:8] = analog_to_maroc[8:8];
  assign page2_analog_to_maroc[6:6] = analog_to_maroc[6:6];
  assign page2_analog_to_maroc[2:2] = analog_to_maroc[2:2];
  assign page2_analog_to_maroc[4:4] = analog_to_maroc[4:4];
  assign page2_analog_to_maroc[0:0] = analog_to_maroc[0:0];
  assign page2_analog_to_maroc[63:63] = analog_to_maroc[63:63];
  assign page2_analog_to_maroc[61:61] = analog_to_maroc[61:61];
  assign page2_analog_to_maroc[57:57] = analog_to_maroc[57:57];
  assign page2_analog_to_maroc[59:59] = analog_to_maroc[59:59];
  assign page2_analog_to_maroc[55:55] = analog_to_maroc[55:55];
  assign page2_analog_to_maroc[53:53] = analog_to_maroc[53:53];
  assign page2_analog_to_maroc[51:51] = analog_to_maroc[51:51];
  assign page2_analog_to_maroc[49:49] = analog_to_maroc[49:49];
  assign page2_analog_to_maroc[47:47] = analog_to_maroc[47:47];
  assign page2_analog_to_maroc[45:45] = analog_to_maroc[45:45];
  assign page2_analog_to_maroc[41:41] = analog_to_maroc[41:41];
  assign page2_analog_to_maroc[43:43] = analog_to_maroc[43:43];
  assign page2_analog_to_maroc[37:37] = analog_to_maroc[37:37];
  assign page2_analog_to_maroc[39:39] = analog_to_maroc[39:39];
  assign page2_analog_to_maroc[35:35] = analog_to_maroc[35:35];
  assign page2_analog_to_maroc[31:31] = analog_to_maroc[31:31];
  assign page2_analog_to_maroc[27:27] = analog_to_maroc[27:27];
  assign page2_analog_to_maroc[29:29] = analog_to_maroc[29:29];
  assign page2_analog_to_maroc[23:23] = analog_to_maroc[23:23];
  assign page2_analog_to_maroc[25:25] = analog_to_maroc[25:25];
  assign page2_analog_to_maroc[19:19] = analog_to_maroc[19:19];
  assign page2_analog_to_maroc[17:17] = analog_to_maroc[17:17];
  assign page2_analog_to_maroc[21:21] = analog_to_maroc[21:21];
  assign page2_analog_to_maroc[15:15] = analog_to_maroc[15:15];
  assign page2_analog_to_maroc[13:13] = analog_to_maroc[13:13];
  assign page2_analog_to_maroc[9:9] = analog_to_maroc[9:9];
  assign page2_analog_to_maroc[11:11] = analog_to_maroc[11:11];
  assign page2_analog_to_maroc[7:7] = analog_to_maroc[7:7];
  assign page2_analog_to_maroc[3:3] = analog_to_maroc[3:3];
  assign page2_analog_to_maroc[5:5] = analog_to_maroc[5:5];
  assign page2_analog_to_maroc[1:1] = analog_to_maroc[1:1];
  assign page2_analog_to_maroc[33:33] = analog_to_maroc[33:33];
  assign page2_analog_to_maroc[22:22] = analog_to_maroc[22:22];
  assign page2_analog_to_maroc[30:30] = analog_to_maroc[30:30];
  assign page2_analog_to_maroc[38:38] = analog_to_maroc[38:38];
  assign page2_analog_to_maroc[63:0] = analog_to_maroc[63:0];
  assign page1_analog_to_maroc[52:52] = analog_to_maroc[52:52];
  assign page1_analog_to_maroc[57:57] = analog_to_maroc[57:57];
  assign page1_analog_to_maroc[62:62] = analog_to_maroc[62:62];
  assign page1_analog_to_maroc[51:51] = analog_to_maroc[51:51];
  assign page1_analog_to_maroc[49:49] = analog_to_maroc[49:49];
  assign page1_analog_to_maroc[48:48] = analog_to_maroc[48:48];
  assign page1_analog_to_maroc[35:35] = analog_to_maroc[35:35];
  assign page1_analog_to_maroc[60:60] = analog_to_maroc[60:60];
  assign page1_analog_to_maroc[58:58] = analog_to_maroc[58:58];
  assign page1_analog_to_maroc[56:56] = analog_to_maroc[56:56];
  assign page1_analog_to_maroc[54:54] = analog_to_maroc[54:54];
  assign page1_analog_to_maroc[50:50] = analog_to_maroc[50:50];
  assign page1_analog_to_maroc[46:46] = analog_to_maroc[46:46];
  assign page1_analog_to_maroc[44:44] = analog_to_maroc[44:44];
  assign page1_analog_to_maroc[42:42] = analog_to_maroc[42:42];
  assign page1_analog_to_maroc[38:38] = analog_to_maroc[38:38];
  assign page1_analog_to_maroc[36:36] = analog_to_maroc[36:36];
  assign page1_analog_to_maroc[32:32] = analog_to_maroc[32:32];
  assign page1_analog_to_maroc[30:30] = analog_to_maroc[30:30];
  assign page1_analog_to_maroc[28:28] = analog_to_maroc[28:28];
  assign page1_analog_to_maroc[26:26] = analog_to_maroc[26:26];
  assign page1_analog_to_maroc[24:24] = analog_to_maroc[24:24];
  assign page1_analog_to_maroc[22:22] = analog_to_maroc[22:22];
  assign page1_analog_to_maroc[20:20] = analog_to_maroc[20:20];
  assign page1_analog_to_maroc[18:18] = analog_to_maroc[18:18];
  assign page1_analog_to_maroc[16:16] = analog_to_maroc[16:16];
  assign page1_analog_to_maroc[14:14] = analog_to_maroc[14:14];
  assign page1_analog_to_maroc[12:12] = analog_to_maroc[12:12];
  assign page1_analog_to_maroc[10:10] = analog_to_maroc[10:10];
  assign page1_analog_to_maroc[8:8] = analog_to_maroc[8:8];
  assign page1_analog_to_maroc[6:6] = analog_to_maroc[6:6];
  assign page1_analog_to_maroc[2:2] = analog_to_maroc[2:2];
  assign page1_analog_to_maroc[0:0] = analog_to_maroc[0:0];
  assign page1_analog_to_maroc[63:63] = analog_to_maroc[63:63];
  assign page1_analog_to_maroc[61:61] = analog_to_maroc[61:61];
  assign page1_analog_to_maroc[59:59] = analog_to_maroc[59:59];
  assign page1_analog_to_maroc[55:55] = analog_to_maroc[55:55];
  assign page1_analog_to_maroc[53:53] = analog_to_maroc[53:53];
  assign page1_analog_to_maroc[47:47] = analog_to_maroc[47:47];
  assign page1_analog_to_maroc[45:45] = analog_to_maroc[45:45];
  assign page1_analog_to_maroc[43:43] = analog_to_maroc[43:43];
  assign page1_analog_to_maroc[41:41] = analog_to_maroc[41:41];
  assign page1_analog_to_maroc[37:37] = analog_to_maroc[37:37];
  assign page1_analog_to_maroc[33:33] = analog_to_maroc[33:33];
  assign page1_analog_to_maroc[31:31] = analog_to_maroc[31:31];
  assign page1_analog_to_maroc[29:29] = analog_to_maroc[29:29];
  assign page1_analog_to_maroc[27:27] = analog_to_maroc[27:27];
  assign page1_analog_to_maroc[25:25] = analog_to_maroc[25:25];
  assign page1_analog_to_maroc[23:23] = analog_to_maroc[23:23];
  assign page1_analog_to_maroc[21:21] = analog_to_maroc[21:21];
  assign page1_analog_to_maroc[19:19] = analog_to_maroc[19:19];
  assign page1_analog_to_maroc[15:15] = analog_to_maroc[15:15];
  assign page1_analog_to_maroc[13:13] = analog_to_maroc[13:13];
  assign page1_analog_to_maroc[11:11] = analog_to_maroc[11:11];
  assign page1_analog_to_maroc[9:9] = analog_to_maroc[9:9];
  assign page1_analog_to_maroc[5:5] = analog_to_maroc[5:5];
  assign page1_analog_to_maroc[1:1] = analog_to_maroc[1:1];
  assign page1_analog_to_maroc[39:39] = analog_to_maroc[39:39];
  assign page1_analog_to_maroc[4:4] = analog_to_maroc[4:4];
  assign page1_analog_to_maroc[3:3] = analog_to_maroc[3:3];
  assign page1_analog_to_maroc[7:7] = analog_to_maroc[7:7];
  assign page1_analog_to_maroc[17:17] = analog_to_maroc[17:17];
  assign page1_analog_to_maroc[34:34] = analog_to_maroc[34:34];
  assign page1_analog_to_maroc[40:40] = analog_to_maroc[40:40];
  assign page1_analog_to_maroc[63:0] = analog_to_maroc[63:0];
  assign avdd = glbl.avdd;
  assign page1_avdd = avdd;
  assign gnd_signal = glbl.gnd_signal;
  assign page1_gnd_signal = gnd_signal;

  assign gnd_signal  = glbl.gnd_signal;
  assign avdd  = glbl.avdd;
  assign analog_to_maroc [1] = lemo_grp_a[3];
  assign analog_to_maroc [7] = lemo_grp_a[0];
  assign analog_to_maroc [5] = lemo_grp_a[1];
  assign analog_to_maroc [3] = lemo_grp_a[2];
  assign analog_to_maroc [63] = lemo_grp_h[0];
  assign analog_to_maroc [59] = lemo_grp_h[2];
  assign analog_to_maroc [61] = lemo_grp_h[1];
  assign analog_to_maroc [57] = lemo_grp_h[3];
  assign analog_to_maroc [55] = lemo_grp_g[0];
  assign analog_to_maroc [51] = lemo_grp_g[2];
  assign analog_to_maroc [53] = lemo_grp_g[1];
  assign analog_to_maroc [49] = lemo_grp_g[3];
  assign analog_to_maroc [47] = lemo_grp_f[0];
  assign analog_to_maroc [43] = lemo_grp_f[2];
  assign analog_to_maroc [45] = lemo_grp_f[1];
  assign analog_to_maroc [41] = lemo_grp_f[3];
  assign analog_to_maroc [39] = lemo_grp_e[0];
  assign analog_to_maroc [35] = lemo_grp_e[2];
  assign analog_to_maroc [37] = lemo_grp_e[1];
  assign analog_to_maroc [33] = lemo_grp_e[3];
  assign analog_to_maroc [31] = lemo_grp_d[0];
  assign analog_to_maroc [27] = lemo_grp_d[2];
  assign analog_to_maroc [29] = lemo_grp_d[1];
  assign analog_to_maroc [25] = lemo_grp_d[3];
  assign analog_to_maroc [23] = lemo_grp_c[0];
  assign analog_to_maroc [19] = lemo_grp_c[2];
  assign analog_to_maroc [21] = lemo_grp_c[1];
  assign analog_to_maroc [17] = lemo_grp_c[3];
  assign analog_to_maroc [15] = lemo_grp_b[0];
  assign analog_to_maroc [11] = lemo_grp_b[2];
  assign analog_to_maroc [13] = lemo_grp_b[1];
  assign analog_to_maroc [9] = lemo_grp_b[3];
  assign analog_to_maroc [54] = lemo_grp_j[3];
  assign analog_to_maroc [50] = lemo_grp_j[1];
  assign analog_to_maroc [52] = lemo_grp_j[2];
  assign analog_to_maroc [48] = lemo_grp_j[0];
  assign analog_to_maroc [46] = lemo_grp_k[3];
  assign analog_to_maroc [42] = lemo_grp_k[1];
  assign analog_to_maroc [44] = lemo_grp_k[2];
  assign analog_to_maroc [40] = lemo_grp_k[0];
  assign analog_to_maroc [38] = lemo_grp_l[3];
  assign analog_to_maroc [34] = lemo_grp_l[1];
  assign analog_to_maroc [36] = lemo_grp_l[2];
  assign analog_to_maroc [32] = lemo_grp_l[0];
  assign analog_to_maroc [30] = lemo_grp_m[3];
  assign analog_to_maroc [26] = lemo_grp_m[1];
  assign analog_to_maroc [28] = lemo_grp_m[2];
  assign analog_to_maroc [24] = lemo_grp_m[0];
  assign analog_to_maroc [22] = lemo_grp_n[3];
  assign analog_to_maroc [18] = lemo_grp_n[1];
  assign analog_to_maroc [20] = lemo_grp_n[2];
  assign analog_to_maroc [16] = lemo_grp_n[0];
  assign analog_to_maroc [14] = lemo_grp_o[3];
  assign analog_to_maroc [10] = lemo_grp_o[1];
  assign analog_to_maroc [12] = lemo_grp_o[2];
  assign analog_to_maroc [8] = lemo_grp_o[0];
  assign analog_to_maroc [6] = lemo_grp_p[3];
  assign analog_to_maroc [2] = lemo_grp_p[1];
  assign analog_to_maroc [4] = lemo_grp_p[2];
  assign analog_to_maroc [0] = lemo_grp_p[0];
  assign analog_to_maroc [56] = lemo_grp_i[0];
  assign analog_to_maroc [60] = lemo_grp_i[2];
  assign analog_to_maroc [58] = lemo_grp_i[1];
  assign analog_to_maroc [62] = lemo_grp_i[3];

// begin instances 

  con150p page1_i2  (.a({glbl.avdd, glbl.avdd, glbl.avdd, glbl.avdd, glbl.gnd_signal, glbl.gnd_signal,
	glbl.gnd_signal, \dboard_ssn* , \dboard_mosi* , glbl.gnd_signal, glbl.gnd_signal,
	dboard_ssn, dboard_mosi, glbl.gnd_signal, glbl.gnd_signal, \dboard_miso* ,
	\dboard_sclk* , glbl.gnd_signal, glbl.gnd_signal, dboard_miso, dboard_sclk,
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[63], analog_to_maroc[62],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[61], analog_to_maroc[60],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[59], analog_to_maroc[58],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[57], analog_to_maroc[56],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[55], analog_to_maroc[54],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[53], analog_to_maroc[52],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[51], analog_to_maroc[50],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[49], analog_to_maroc[48],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[47], analog_to_maroc[46],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[45], analog_to_maroc[44],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[43], analog_to_maroc[42],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[41], analog_to_maroc[40],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[39], analog_to_maroc[38],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[37], analog_to_maroc[36],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[35], analog_to_maroc[34],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[33], analog_to_maroc[32],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[31], analog_to_maroc[30],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[29], analog_to_maroc[28],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[27], analog_to_maroc[26],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[25], analog_to_maroc[24],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[23], analog_to_maroc[22],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[21], analog_to_maroc[20],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[19], analog_to_maroc[18],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[17], analog_to_maroc[16],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[15], analog_to_maroc[14],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[13], analog_to_maroc[12],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[11], analog_to_maroc[10],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[9], analog_to_maroc[8],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[7], analog_to_maroc[6],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[5], analog_to_maroc[4],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[3], analog_to_maroc[2],
	glbl.gnd_signal, glbl.gnd_signal, analog_to_maroc[1], analog_to_maroc[0],
	glbl.gnd_signal}));

  pc049a_4lemos page2_i1  (.analog_in(lemo_grp_a[3:0]));

  pc049a_4lemos page2_i18  (.analog_in(lemo_grp_h[3:0]));

  pc049a_4lemos page2_i27  (.analog_in(lemo_grp_g[3:0]));

  pc049a_4lemos page2_i36  (.analog_in(lemo_grp_f[3:0]));

  pc049a_4lemos page2_i45  (.analog_in(lemo_grp_e[3:0]));

  pc049a_4lemos page2_i54  (.analog_in(lemo_grp_d[3:0]));

  pc049a_4lemos page2_i63  (.analog_in(lemo_grp_c[3:0]));

  pc049a_4lemos page2_i72  (.analog_in(lemo_grp_b[3:0]));

  pc049a_4lemos page2_i137  (.analog_in(lemo_grp_i[3:0]));

  pc049a_4lemos page2_i138  (.analog_in(lemo_grp_k[3:0]));

  pc049a_4lemos page2_i139  (.analog_in(lemo_grp_j[3:0]));

  pc049a_4lemos page2_i140  (.analog_in(lemo_grp_m[3:0]));

  pc049a_4lemos page2_i141  (.analog_in(lemo_grp_n[3:0]));

  pc049a_4lemos page2_i142  (.analog_in(lemo_grp_l[3:0]));

  pc049a_4lemos page2_i143  (.analog_in(lemo_grp_p[3:0]));

  pc049a_4lemos page2_i144  (.analog_in(lemo_grp_o[3:0]));

endmodule // pc049a_lemo_daughter_board(sch_1) 
