//------------------------------------------------------------------------------
// File       : demo_tb.v
// Author     : Xilinx Inc.
//------------------------------------------------------------------------------
// (c) Copyright 2009 Xilinx, Inc. All rights reserved.
//
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
//
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
//
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
//
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 
//
//
//------------------------------------------------------------------------------
// Description: This testbench will exercise the ports of the Ethernet
// 1000BASE-X PCS/PMA core's example design to perform the following
// operations:
//
//----------------
//  Configuration
//----------------
//  The core will be reset, then Auto-Negotiation (if present) will
//  be disabled and and the core will be taken out of the Isolate
//  state.
//
//----------------
//  Transmitter
//----------------
//  Four frames are generated by the Tx Stimulus and pushed into the
//  GMII transmitter.
//
//  The PHY side transmitter interface data is captured, 8B10B decoded
//  and the Tx Monitor checks that the captured data matches that
//  injected.
//
//----------------
//  Receiver
//----------------
//  Four frames are generated by the Rx Stimulus, 8B10B encoded and
//  pushed into the PHY side receiver interface.
//
//  The GMII side receiver interface data is captured and the
//  Rx Monitor checks that the captured data matches that injected.
//
//
//----------------------------------------------------------------------
//                  Demonstration Test Fixture                         |
//                                                                     |
//                                                                     |
//                  --------------------------                         |
//                  |     Example Design     |                         |
//                  |         (DUT)          |                         |
//                  |                        |                         |
//                  |                        |                         |
//                  |                        |                         |
//   Tx             |                        |  8B10B decode, Tx       |
//   Generate   ------->                  -------->           Monitor  |
//   Frames         |                        |                Frames   |
//                  |GMII                PHY |                         |
//                  | I/F                I/F |                         |
//                  |                        |                         |
//                  |                        |                         |
//                  |                        |                         |
//    Rx            |                        |  8B10B encode, Rx       |
//    Monitor  <--------                  <--------           Generate |
//    Frames        |                        |                Frames   |
//                  |                        |                         |
//                  ------------^-------------                         |
//                              |                                      |
//                              |                                      |
//                          Stimulate                                  |
//                          MDIO I/F                                   |
//                         (if present)                                |
//                                                                     |
//----------------------------------------------------------------------

`timescale 1 ps/1 ps



// This module is the demonstration testbench
module demo_tb;





  //----------------------------------------------------------------------------
  // testbench signals
  //----------------------------------------------------------------------------

  // testbench control semaphores
  reg  configuration_finished;
  wire tx_monitor_finished0;
  wire rx_monitor_finished0;
  wire simulation_finished;


  //----------------------------------------------------------------------------
  // DUT signals
  //----------------------------------------------------------------------------

  // System Reset
  reg  reset;

  // Management: Alternative to MDIO Interface
  //------------------------------------------
  reg [4:0] configuration_vector;

  // Transceiver Interface
  //----------------------
  reg  brefclk_p;
  reg  brefclk_n;

  wire txp0;
  wire txn0;
  wire rxp0;
  wire rxn0;

  wire txp1;
  wire txn1;
  wire rxp1;
  wire rxn1;

  //-------------------------
  // Core connected to GTP/X0
  //-------------------------

  // GMII Interface
  //---------------
  wire gmii_tx_clk0;
  wire gmii_rx_clk0;
  wire [7:0] gmii_txd0;
  wire gmii_tx_en0;
  wire gmii_tx_er0;
  wire [7:0] gmii_rxd0;
  wire gmii_rx_dv0;
  wire gmii_rx_er0;


  // Other IO's
  //-----------
  wire [15:0] status_vector0;
  wire signal_detect0;



  //----------------------------------------------------------------------------
  // Create clock sources
  //----------------------------------------------------------------------------

  // Create the RocketIO Reference clock (125 MHz)
  initial
  begin
    brefclk_p <= 1'b0;
    brefclk_n <= 1'b1;
    forever
    begin
      brefclk_p <= 1'b0;
      brefclk_n <= 1'b1;
      #4000;
      brefclk_p <= 1'b1;
      brefclk_n <= 1'b0;
      #4000;
    end
  end



  //----------------------------------------------------------------------------
  // Wire up Device Under Test
  //----------------------------------------------------------------------------
  gig_eth_pcs_pma_v11_4_example_design dut
     (
      .gmii_tx_clk0           (gmii_tx_clk0),
      .gmii_rx_clk0           (gmii_rx_clk0),
      .gmii_txd0              (gmii_txd0),
      .gmii_tx_en0            (gmii_tx_en0),
      .gmii_tx_er0            (gmii_tx_er0),
      .gmii_rxd0              (gmii_rxd0),
      .gmii_rx_dv0            (gmii_rx_dv0),
      .gmii_rx_er0            (gmii_rx_er0),
      .configuration_vector0  (configuration_vector),
      .status_vector0         (status_vector0),
      .reset0                 (reset),
      .signal_detect0         (signal_detect0),
      .brefclk_p              (brefclk_p),
      .brefclk_n              (brefclk_n),
      .txp0                   (txp0),
      .txn0                   (txn0),
      .rxp0                   (rxp0),
      .rxn0                   (rxn0),
      .txp1                   (txp1),
      .txn1                   (txn1),
      .rxp1                   (rxp1),
      .rxn1                   (rxn1)
      );



  //----------------------------------------------------------------------------
  // Instantiate a Stimulus module for the core connected to transceiver 0
  //----------------------------------------------------------------------------
  stimulus_tb #
  (
      .INSTANCE_NUMBER        (0)
  )
  stimulus_0
  (
      .txp                    (txp0),
      .txn                    (txn0),
      .rxp                    (rxp0),
      .rxn                    (rxn0),

      .gmii_tx_clk            (gmii_tx_clk0),
      .gmii_rx_clk            (gmii_rx_clk0),
      .gmii_txd               (gmii_txd0),
      .gmii_tx_en             (gmii_tx_en0),
      .gmii_tx_er             (gmii_tx_er0),
      .gmii_rxd               (gmii_rxd0),
      .gmii_rx_dv             (gmii_rx_dv0),
      .gmii_rx_er             (gmii_rx_er0),

      .configuration_finished (configuration_finished),
      .tx_monitor_finished    (tx_monitor_finished0),
      .rx_monitor_finished    (rx_monitor_finished0)
  );


  // transceiver 1 is unused
  assign rxp1 = 1'b0;
  assign rxn1 = 1'b1;



  //----------------------------------------------------------------------------
  // Simulate that PMD sublayer has detected and optical input.
  //----------------------------------------------------------------------------
  assign signal_detect0 = 1'b1;


  //----------------------------------------------------------------------------
  // Set the configuration for the core.  Any of the bits within
  // "configuration_vector" can be changed dynamically.
  // The core is then reset
  //----------------------------------------------------------------------------
  initial
  begin : p_configuration
    $display("** Note: Timing checks are not valid");

    configuration_finished <= 0;

    configuration_vector[1:0] <= 2'h0;   // Disable Loopback
    configuration_vector[2]   <= 1'b0;   // Disable POWERDOWN
    configuration_vector[3]   <= 1'b0;   // Disable ISOLATE
    configuration_vector[4]   <= 1'b0;   // Enable  Auto-Neg

    // reset the core
    $display("Resetting core...");
    reset <= 1'b1;
    #5000000
    @(posedge brefclk_p)
    reset <= 1'b0;
    // wait for core to obtain synchronisation
    wait (status_vector0[0] == 1);
    #2000000

    @(posedge brefclk_p)

    configuration_finished <= 1;
  end // p_configuration



  //----------------------------------------------------------------------------
  // End the simulation.
  //----------------------------------------------------------------------------

  assign simulation_finished = tx_monitor_finished0 & rx_monitor_finished0;

  initial
  begin : p_end_simulation
  fork: sim_in_progress
     @(posedge simulation_finished) disable sim_in_progress;
     #200000000                     disable sim_in_progress;
  join
  if (simulation_finished)
       #1000000
       $display("Simulation Complete.");
  else
     $display("** Error: Testbench timed out");
  $stop;
  end // p_end_simulation



endmodule

