`timescale 1ns/1ns

module pc049a_4lemos (analog_in );
// generated by  HDL Direct 16.5-S016 (v16-5-13AQ) 2/14/2012
// on Mon Mar 17 15:01:00 2014
// from uob_hep_pc049a_lib/PC049A_4LEMOS/sch_1

  output [3:0] analog_in;
  // global signal glbl.gnd_signal;

  wire  unnamed_1_capn4i_i10_a;
  wire  unnamed_1_capn4i_i10_a_1;
  wire  unnamed_1_capn4i_i10_a_2;
  wire  unnamed_1_capn4i_i10_a_3;

  wire [3:0] page1_analog_in;
  wire  gnd_signal;
  wire  page1_gnd_signal;

  assign page1_analog_in[0:0] = analog_in[0:0];
  assign page1_analog_in[2:2] = analog_in[2:2];
  assign page1_analog_in[1:1] = analog_in[1:1];
  assign page1_analog_in[3:3] = analog_in[3:3];
  assign page1_analog_in[3:0] = analog_in[3:0];
  assign gnd_signal = glbl.gnd_signal;
  assign page1_gnd_signal = gnd_signal;

  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;

// begin instances 

  capn4i page1_i10  (.a({unnamed_1_capn4i_i10_a_3, unnamed_1_capn4i_i10_a_2, unnamed_1_capn4i_i10_a_1,
	unnamed_1_capn4i_i10_a}),
	.b({analog_in[0], analog_in[1], analog_in[2], analog_in[3]}));
  defparam page1_i10.size = 4;

  coax page1_i11  (.a(unnamed_1_capn4i_i10_a_3),
	.b({open_p1$1, open_p1$2, open_p1$3, glbl.gnd_signal}));

  prtr5v0u4y page1_i12  (.esd1(unnamed_1_capn4i_i10_a_2),
	.esd2(unnamed_1_capn4i_i10_a_3),
	.esd3(unnamed_1_capn4i_i10_a),
	.esd4(unnamed_1_capn4i_i10_a_1),
	.gnd(glbl.gnd_signal),
	.vcc(glbl.gnd_signal));

  coax page1_i15  (.a(unnamed_1_capn4i_i10_a),
	.b({open_p1$4, open_p1$5, open_p1$6, glbl.gnd_signal}));

  coax page1_i17  (.a(unnamed_1_capn4i_i10_a_1),
	.b({open_p1$7, open_p1$8, open_p1$9, glbl.gnd_signal}));

  coax page1_i19  (.a(unnamed_1_capn4i_i10_a_2),
	.b({open_p1$10, open_p1$11, open_p1$12, glbl.gnd_signal}));

endmodule // pc049a_4lemos(sch_1) 
