// generated by newgenasym  Thu Mar 13 15:25:04 2014


module pc043c_single_maroc (adc_dav, analog_in, ck_40m, ck_r, ck_sc, ckb_40m, ctest,
        d_r, d_sc, en_otag, hold1, hold2, \or , out_adc, qbuf_r,
        qbuf_sc, rstb_r, rstn_adc, rstn_sc, start_adcb, sum, trig);
    output adc_dav;
    input [63:0] analog_in;
    input ck_40m;
    input ck_r;
    input ck_sc;
    input ckb_40m;
    input ctest;
    input d_r;
    input d_sc;
    input en_otag;
    input hold1;
    input hold2;
    output [1:0] \or ;
    output out_adc;
    output qbuf_r;
    output qbuf_sc;
    input rstb_r;
    input rstn_adc;
    input rstn_sc;
    input start_adcb;
    output [8:1] sum;
    output [63:0] trig;


    initial
        begin
        end

endmodule
