-- generated by newgenasym Thu Mar 13 15:25:04 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pc043c_single_maroc is
    port (    
	ADC_DAV:   OUT    std_logic;    
	ANALOG_IN: IN     std_logic_vector (63 DOWNTO 0);    
	CK_40M:    IN     std_logic;    
	CK_R:      IN     std_logic;    
	CK_SC:     IN     std_logic;    
	CKB_40M:   IN     std_logic;    
	CTEST:     IN     std_logic;    
	D_R:       IN     std_logic;    
	D_SC:      IN     std_logic;    
	EN_OTAG:   IN     std_logic;    
	HOLD1:     IN     std_logic;    
	HOLD2:     IN     std_logic;    
	\or\:      OUT    std_logic_vector (1 DOWNTO 0);    
	OUT_ADC:   OUT    std_logic;    
	QBUF_R:    OUT    std_logic;    
	QBUF_SC:   OUT    std_logic;    
	RSTB_R:    IN     std_logic;    
	RSTN_ADC:  IN     std_logic;    
	RSTN_SC:   IN     std_logic;    
	START_ADCB: IN     std_logic;    
	SUM:       OUT    std_logic_vector (8 DOWNTO 1);    
	TRIG:      OUT    std_logic_vector (63 DOWNTO 0));
end pc043c_single_maroc;
